# Generated by Django 4.2.11 on 2024-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
