# Generated by Django 4.2.11 on 2024-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="humidity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="operational_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="temperature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
